package restsuured;

import static  io.restassured.RestAssured.*;
import static io.restassured.matcher.RestAssuredMatchers.*;
import static org.hamcrest.Matchers.*;

import org.json.JSONObject;
import org.testng.ITestContext;
import org.testng.annotations.Test;

import com.github.javafaker.Faker;
import com.google.gson.JsonObject;


public class createuser {
	
	/*Response from one Request will become the Requset for another Request is called APIChaining process
	 * We can do this chaining process following website (Go  rest)
	 * To access this API'S we need token below the UI of these website there is a option called generate token 
	 * with that we can get the token and we ahve to use that token to access the API'S
	 *  Token---436db33d3ce350456d7f970e9597f381efb2cefe5e005060d4ad6563397c6232
	 * */
	 
	/*--------------------ITESTCONTEXT-------------
	 * we are creating createuser,getuser.updateuser,deleteuser in different classes adn trying to use the id 
	 * generated by the create user to next all the classes in order to capture the generated id we will
	 *  ITEXTCONTEXT interface and context is the variable here, this contect variable holeds the entire context
	 *  of the response returned by the creteuser method from that we are using id by cerating context.setattributr("user_id,id)
	 *  Here we can conisder this id as a environmental variable like in POSTMAN 
	 *  context.setattribute("user_id",id)--------for test level--only to one test
	 *  context.getsuit().setattribute("user_id",id)--------for suit level-suitabele to all tests in package
	 *  
	 *  After we are setting this attribute we need to set this attribute 
	 *  
	 * 
	 */
	@Test
	public void cuser(ITestContext context) {
		
		Faker fk=new Faker();
		JSONObject dt=new JSONObject();
		
		dt.put("name",fk.name().fullName() );
		dt.put("gender","Male" );
		dt.put("email",fk.internet().emailAddress() );
		dt.put("status","inactive");
		
		String s=new String("436db33d3ce350456d7f970e9597f381efb2cefe5e005060d4ad6563397c6232");
		
             int id=given()
              .contentType("application/json")
              .header("Authorization","Bearer "+s)
              .body(dt.toString())  //when ur passing json data we must use tostring method
            
		
		     .when()
		    .post("https://reqres.in/api/users?page=2")
		    .jsonPath().getInt("id");
		
		
		System.out.println("Default generated id is: "+ id);
		
		context.getSuite().setAttribute("user_id", id);
		
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
